import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "next-themes";
import ReactQueryProviders from "./hooks/useReactQuery";
import RecoilRootWrapper from "./hooks/useRecoilRootWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <ReactQueryProviders>
            <RecoilRootWrapper>{children}</RecoilRootWrapper>
          </ReactQueryProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
